# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LlmLog < Formula
  desc "Local proxy that tracks tokens, costs, prompts and responses across all LLM API calls"
  homepage "https://github.com/lanesket/llm.log"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lanesket/llm.log/releases/download/v0.1.0/llm.log_darwin_amd64.tar.gz"
      sha256 "52de5360fada76c7c9e161fe59caaaa9357b5d66162575a8810251abbb104dfd"

      define_method(:install) do
        bin.install "llm-log"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lanesket/llm.log/releases/download/v0.1.0/llm.log_darwin_arm64.tar.gz"
      sha256 "36d2c30a33cf1593483ef1c9d47543ea9a55594baee7f215ca2c7958b9871703"

      define_method(:install) do
        bin.install "llm-log"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lanesket/llm.log/releases/download/v0.1.0/llm.log_linux_amd64.tar.gz"
      sha256 "bfb4fb3f109f32ff5a604ce9aa09e1a2dd0b10e8c2e1d3393b229a23ba3ff428"
      define_method(:install) do
        bin.install "llm-log"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lanesket/llm.log/releases/download/v0.1.0/llm.log_linux_arm64.tar.gz"
      sha256 "a8f177e2ca5bedc6d10d04b887eccffe3ddee28917fd7620e6e041da42a949b0"
      define_method(:install) do
        bin.install "llm-log"
      end
    end
  end
end
