# This file was generated by GoReleaser. DO NOT EDIT.
cask "llm.log" do
  name "llm.log"
  desc "Local proxy that tracks tokens, costs, prompts and responses across all LLM API calls"
  homepage "https://github.com/lanesket/llm.log"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "llm.log"

  on_macos do
    on_intel do
      url "https://github.com/lanesket/llm.log/releases/download/v#{version}/llm.log_darwin_amd64.tar.gz"
      sha256 "e1de7e36b67b9c36ca6291ebef82450c4728141519dbe770d405c3c7af4f52db"
    end
    on_arm do
      url "https://github.com/lanesket/llm.log/releases/download/v#{version}/llm.log_darwin_arm64.tar.gz"
      sha256 "e50dd40a9e6271e2a4cf51790e4348f6e9b484aa383e0062819564f4e14a8a56"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lanesket/llm.log/releases/download/v#{version}/llm.log_linux_amd64.tar.gz"
      sha256 "548e634bdf21197f03a799c5623ec95d7d2a4ff5b187b0174aaa7705e1e35df6"
    end
    on_arm do
      url "https://github.com/lanesket/llm.log/releases/download/v#{version}/llm.log_linux_arm64.tar.gz"
      sha256 "1f222d5830d0142a31679aa50bfedb30a82794b403797f5c22aed9ce50fbf243"
    end
  end

  # No zap stanza required
end
