# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LlmLog < Formula
  desc "Local proxy that tracks tokens, costs, prompts and responses across all LLM API calls"
  homepage "https://github.com/lanesket/llm.log"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lanesket/llm.log/releases/download/v0.4.1/llm.log_darwin_amd64.tar.gz"
      sha256 "b45bbfd40263e478b2e73d2f4589bf31a29c77059dd1115910e5e4a651b1c039"

      define_method(:install) do
        bin.install "llm-log"
        bash_completion.install "completions/llm-log.bash" => "llm-log"
        zsh_completion.install "completions/llm-log.zsh" => "_llm-log"
        fish_completion.install "completions/llm-log.fish" => "llm-log.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lanesket/llm.log/releases/download/v0.4.1/llm.log_darwin_arm64.tar.gz"
      sha256 "bd789085d26ed4d4be67c7ac58aa4083cbfea5aa71d6ad736c4e361312aeab37"

      define_method(:install) do
        bin.install "llm-log"
        bash_completion.install "completions/llm-log.bash" => "llm-log"
        zsh_completion.install "completions/llm-log.zsh" => "_llm-log"
        fish_completion.install "completions/llm-log.fish" => "llm-log.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lanesket/llm.log/releases/download/v0.4.1/llm.log_linux_amd64.tar.gz"
      sha256 "d84a7d6b01e1e6c7b8cf466075872a76accc0e0d3e9216ea746da3dd4c4ea18c"
      define_method(:install) do
        bin.install "llm-log"
        bash_completion.install "completions/llm-log.bash" => "llm-log"
        zsh_completion.install "completions/llm-log.zsh" => "_llm-log"
        fish_completion.install "completions/llm-log.fish" => "llm-log.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lanesket/llm.log/releases/download/v0.4.1/llm.log_linux_arm64.tar.gz"
      sha256 "d970a63af8134f5f60f938f603ddc6528be809767f522609eea8ee782a1b2fe8"
      define_method(:install) do
        bin.install "llm-log"
        bash_completion.install "completions/llm-log.bash" => "llm-log"
        zsh_completion.install "completions/llm-log.zsh" => "_llm-log"
        fish_completion.install "completions/llm-log.fish" => "llm-log.fish"
      end
    end
  end

  test do
    system "#{bin}/llm-log", "--version"
  end
end
