# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LlmLog < Formula
  desc "Local proxy that tracks tokens, costs, prompts and responses across all LLM API calls"
  homepage "https://github.com/lanesket/llm.log"
  version "0.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lanesket/llm.log/releases/download/v0.4.2/llm.log_darwin_amd64.tar.gz"
      sha256 "86a317168b1da3bab205b25fa311aacb1dca2fe377b1de8f95d9bde47341def4"

      define_method(:install) do
        bin.install "llm-log"
        bash_completion.install "completions/llm-log.bash" => "llm-log"
        zsh_completion.install "completions/llm-log.zsh" => "_llm-log"
        fish_completion.install "completions/llm-log.fish" => "llm-log.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lanesket/llm.log/releases/download/v0.4.2/llm.log_darwin_arm64.tar.gz"
      sha256 "2d7c518beba206e73eade694e712f34dca7e5c6f5f73f716ad04b98d4a075834"

      define_method(:install) do
        bin.install "llm-log"
        bash_completion.install "completions/llm-log.bash" => "llm-log"
        zsh_completion.install "completions/llm-log.zsh" => "_llm-log"
        fish_completion.install "completions/llm-log.fish" => "llm-log.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lanesket/llm.log/releases/download/v0.4.2/llm.log_linux_amd64.tar.gz"
      sha256 "38dfe60984ee79f19995d5499002f1b732621f8dc26fd038ba65df9151cb2c28"
      define_method(:install) do
        bin.install "llm-log"
        bash_completion.install "completions/llm-log.bash" => "llm-log"
        zsh_completion.install "completions/llm-log.zsh" => "_llm-log"
        fish_completion.install "completions/llm-log.fish" => "llm-log.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lanesket/llm.log/releases/download/v0.4.2/llm.log_linux_arm64.tar.gz"
      sha256 "7a2177b6ef60b4f2733f5cf0f6360d477df0e8365677282cdc029abfc6fdd35f"
      define_method(:install) do
        bin.install "llm-log"
        bash_completion.install "completions/llm-log.bash" => "llm-log"
        zsh_completion.install "completions/llm-log.zsh" => "_llm-log"
        fish_completion.install "completions/llm-log.fish" => "llm-log.fish"
      end
    end
  end

  test do
    system "#{bin}/llm-log", "--version"
  end
end
