# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LlmLog < Formula
  desc "Local proxy that tracks tokens, costs, prompts and responses across all LLM API calls"
  homepage "https://github.com/lanesket/llm.log"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lanesket/llm.log/releases/download/v0.2.0/llm.log_darwin_amd64.tar.gz"
      sha256 "6e4e33480646cbda9e379c8c91c50bfd38bf1cbc99e2ab9198d41465548d2633"

      define_method(:install) do
        bin.install "llm-log"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lanesket/llm.log/releases/download/v0.2.0/llm.log_darwin_arm64.tar.gz"
      sha256 "cfeb0333d7919e858f084b01207864840a6264752d4978ab81e417909afa6152"

      define_method(:install) do
        bin.install "llm-log"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lanesket/llm.log/releases/download/v0.2.0/llm.log_linux_amd64.tar.gz"
      sha256 "36b1bd9360a8730d5175c1b97f3d19a9c1b51ce8e519fb6ea6aa1d776ee72ceb"
      define_method(:install) do
        bin.install "llm-log"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lanesket/llm.log/releases/download/v0.2.0/llm.log_linux_arm64.tar.gz"
      sha256 "c642e13236debb9341f7a4c2e822954dfbf60d01f11345cfa6a12719176a506b"
      define_method(:install) do
        bin.install "llm-log"
      end
    end
  end

  test do
    system "#{bin}/llm-log", "--version"
  end
end
